[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "chmod -R 777 /data && n8n start
"

[variables]
# Required for Railway deployment
N8N_PORT = "5678"
WEBHOOK_TUNNEL_URL = ""
N8N_HOST = "0.0.0.0"

# Basic Auth (optional but recommended)
N8N_BASIC_AUTH_ACTIVE = "true"
N8N_BASIC_AUTH_USER = "admin"
N8N_BASIC_AUTH_PASSWORD = "YOUR_KEY_VALUE"

# Encryption key for credentials
N8N_ENCRYPTION_KEY = "YOUR_KEY_VALUE"

# Make sure n8n saves data on the Railway volume
N8N_PATH = "/data"
EXECUTIONS_DATA_SAVE_ON_ERROR = "all"
EXECUTIONS_DATA_SAVE_ON_SUCCESS = "none"
GENERIC_TIMEZONE = "Asia/Kolkata"

